### PR TITLE
New UI & 1 Bug Fix

### LINKED ISSUE #69: Color setting issue
When I was trying to set the colors, I found that saving would automatically convert the hex color code to uppercase.
It was normal when saving, but when I re-entered the settings page, I found that the displayed color was different from what I set. However, the actual color displayed on the webpage is the one I set.
This issue occurs whenever the saved content is in uppercase.
image
image

### PR DESCRIPTION
**Pull request by WiLuX-Source**
Hello Revadike, This is the new UI I've been working on 4 days.

It also fixes #69

### CODE REVIEW

File: scripts/popup.js [hunk 1]
```diff
@@ -13,7 +15,7 @@ async function setSettings(newSettings) {
 function showToast() {
     const toast = document.getElementById("snackbar");
     toast.classList.add("show");
-    setTimeout(() => toast.classList.remove("show"), 3000);
+    setTimeout(() => toast.classList.remove("show"), 2900);
```
Comment (Revadike) [inline scripts/popup.js:18]: any reason to show it 100 ms less? 🤔

Comment (WiLuX-Source) [reply scripts/popup.js:18]: The old one was glitching for me this did the trick.
